# Generated by Django 4.2.3 on 2024-01-17 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishlistModel',
        ),
    ]
