# Generated by Django 4.2.3 on 2024-01-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GenreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('image', models.ImageField(upload_to='images/books')),
                ('isbn', models.CharField(max_length=50)),
                ('stock', models.IntegerField()),
                ('availability', models.BooleanField(default=True)),
                ('publication_date', models.DateField()),
                ('total_page', models.IntegerField()),
                ('cover', models.CharField(choices=[('paperback', 'Paper Back'), ('hardcover', 'Hard Cover')], max_length=50)),
                ('genre', models.ManyToManyField(to='book.genremodel')),
            ],
        ),
    ]
