# Generated by Django 4.2.3 on 2024-01-16 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmodel',
            name='language',
            field=models.CharField(default='english', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookmodel',
            name='description',
            field=models.TextField(),
        ),
    ]
